[package]
name = "effy"
version = "0.0.0"
authors = ["Ralph Minderhoud <mail@ralphminderhoud.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "1.0"
quote = "1.0"
proc-macro2 = "1.0"

