[package]
name = "effy-support"
version = "0.1.0"
authors = ["Ralph Minderhoud <mail@ralphminderhoud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
